#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="dokku/$APP"
COMMAND=$(cat <<EOF

export DEBIAN_FRONTEND=noninteractive
apt-get -y  update 
apt-get install -y wget xfonts-base xfonts-75dpi
cd /tmp && wget http://download.gna.org/wkhtmltopdf/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
cd /tmp && tar xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
mv /tmp/wkhtmltox /opt/
cd /usr/local/bin && ln -s /opt/wkhtmltox/bin/wkhtmltopdf
echo "-----> wkhtmltox installed!"
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)

if [ "$INSTALL_WKHTMLTOX" = "false" ]
then
  echo "-----> skipping wkhtmltox install..."
else
  echo "-----> Installing wkhtmltox ..."
  id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
  #enable logs
  docker attach $id
  test $(docker wait $id) -eq 0
  docker commit $id $IMAGE > /dev/null
fi